name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Repository Files
        run: |
          echo "Listing all files..."
          ls -R Frontend/registerFrontEnd/dist/

      - name: Deploy Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Frontend/registerFrontEnd/dist/*"
          target: "/home/vision/htdocs/vision.trentynnicholas.com/"
          strip_components: 1
          rm: true

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Backend to VPS (Exclude upload directories)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Backend/*"
          target: "/home/trentynnicholas-api-vision/htdocs/api.vision.trentynnicholas.com/backend/"
          strip_components: 1
          rsync_opts: "--exclude=uploads/ --exclude=socialIcons/ --exclude=galleryuploads/"

      - name: Ensure upload folders exist on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Ensuring upload directories exist..."
            mkdir -p /home/trentynnicholas-api-vision/htdocs/api.vision.trentynnicholas.com/backend/uploads
            mkdir -p /home/trentynnicholas-api-vision/htdocs/api.vision.trentynnicholas.com/backend/socialIcons
            mkdir -p /home/trentynnicholas-api-vision/htdocs/api.vision.trentynnicholas.com/backend/galleryuploads
            chmod -R 755 /home/trentynnicholas-api-vision/htdocs/api.vision.trentynnicholas.com/backend/uploads
            chmod -R 755 /home/trentynnicholas-api-vision/htdocs/api.vision.trentynnicholas.com/backend/socialIcons
            chmod -R 755 /home/trentynnicholas-api-vision/htdocs/api.vision.trentynnicholas.com/backend/galleryuploads
            echo "All upload directories ensured on VPS."

      - name: Install Dependencies on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Installing dependencies..."
            cd /home/trentynnicholas-api-vision/htdocs/api.vision.trentynnicholas.com/backend
            npm install --production
            echo "Restarting backend service..."
            pm2 restart bakersburns

      - name: Restart Backend Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Restarting backend service..."
            pm2 restart bakersburns


  deploy-admin:
    if: false
    name: Deploy Admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Admin Files
        run: |
          echo "Listing Admin Frontend dist folder..."
          ls -R Frontend/adminFrontEnd/dist/

      - name: Deploy Admin to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Frontend/adminFrontEnd/dist/*"
          target: "/home/bakersburns-admin/htdocs/admin.bakersburns.com/"
          strip_components: 3
          rm: true

  deploy-user:
    if: false
    name: Deploy User Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug User Files
        run: |
          echo "Listing User Frontend dist folder..."
          ls -R Frontend/userFrontEnd/dist/

      - name: Deploy User Interface to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "Frontend/userFrontEnd/dist/*"
          target: "/home/bakersburns-user/htdocs/user.bakersburns.com/"
          strip_components: 3
          rm: true
          
