name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Files in Repo
        run: |
          echo "Checking repo contents..."
          ls -R dist/

      - name: Deploy Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/**"
          target: "/home/vision/htdocs/vision.trentynnicholas.com/"
          strip_components: 1
          rm: true
